### PR TITLE
Bump versioneer to 0.29

### PR DESCRIPTION
**Pull request by sliedes**
The existing version of versioneer, 0.18, does not work in Python 3.12:

```
    File "/build/eliot-tree-21.0.0/versioneer.py", line 342, in get_config_from_root
      parser = configparser.SafeConfigParser()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

Update it to 0.29.

- - -
This change is [Reviewable](https://reviewable.io/reviews/jonathanj/eliottree/105)

### CODE REVIEW

**Comment by jonathanj** [comment]
This is now in version 24.0.0, thanks again!
